name = "Hellscape"
author = "Cronus"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc9f9af005824d648a7831abb5d20aff9d7cea215834f3ab6b49374e466dd7ed"

[versions]
fabric = "0.14.12"
minecraft = "1.18.2"
