name = "Hellscape"
author = "Cronus"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4efd824c29d304a02ebb46ebee89fdab14a7571764ad52bd447503ac3dfb1797"

[versions]
fabric = "0.14.12"
minecraft = "1.18.2"
