name = "Hellscape"
author = "Cronus"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9f6303b3700c025bff436706a854c01e2fa4db1c5b00b6ae26cd2b5ccad7a03"

[versions]
fabric = "0.14.12"
minecraft = "1.18.2"
